-- Phase 5 — Social Media Analytics Platform
-- Full Snowflake schema: RAW → CURATED → ANALYTICS
-- ── DATABASE ──────────────────────────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS SOCIAL_MEDIA_DB;
USE DATABASE SOCIAL_MEDIA_DB;
-- ── RAW LAYER ─────────────────────────────────────────────────────────────────
-- Stores every event exactly as it arrived, before any transformation.
-- Nothing is changed here — this is the immutable source of truth.
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE TABLE IF NOT EXISTS RAW.RAW_EVENTS (
    event_id VARCHAR,
    -- UUID generated by simulator
    event_type VARCHAR,
    -- POST_CREATED / LIKE / COMMENT / SHARE / FOLLOW / VIDEO_VIEW / PROFILE_VISIT
    user_id VARCHAR,
    -- who triggered the event
    post_id VARCHAR,
    -- which post (NULL for FOLLOW, PROFILE_VISIT)
    target_user_id VARCHAR,
    -- recipient (FOLLOW, PROFILE_VISIT)
    hashtags VARIANT,
    -- JSON array of hashtag strings (POST_CREATED only)
    comment_text VARCHAR,
    -- text content (COMMENT only)
    content_type VARCHAR,
    -- image / video / text / reel / story (POST_CREATED)
    video_duration_sec FLOAT,
    -- total video length (VIDEO_VIEW)
    watch_time_sec FLOAT,
    -- how long user watched (VIDEO_VIEW)
    raw_payload VARIANT,
    -- full original JSON — never lose anything
    event_timestamp TIMESTAMP,
    -- when the event happened (from simulator)
    ingested_at TIMESTAMP,
    -- when Spark wrote it to Snowflake
    is_valid BOOLEAN,
    -- FALSE if validation failed
    validation_errors VARCHAR -- description of what was wrong (if any)
);
-- ── CURATED LAYER ─────────────────────────────────────────────────────────────
-- Cleaned, enriched, joined data. Dimension tables + fact table.
CREATE SCHEMA IF NOT EXISTS CURATED;
-- dimension table: one row per user, static reference data
CREATE TABLE IF NOT EXISTS CURATED.USER_DIM (
    user_id VARCHAR PRIMARY KEY,
    username VARCHAR,
    user_type VARCHAR,
    -- regular / influencer / brand
    follower_count INTEGER,
    following_count INTEGER,
    post_count INTEGER,
    country VARCHAR,
    created_at TIMESTAMP
);
-- dimension table: one row per post, static reference data
CREATE TABLE IF NOT EXISTS CURATED.POST_DIM (
    post_id VARCHAR PRIMARY KEY,
    user_id VARCHAR,
    -- who created it
    content_type VARCHAR,
    hashtags VARIANT,
    -- JSON array
    created_at TIMESTAMP
);
-- enriched events: raw events joined with USER_DIM and POST_DIM
CREATE TABLE IF NOT EXISTS CURATED.CURATED_EVENTS (
    event_id VARCHAR,
    event_type VARCHAR,
    user_id VARCHAR,
    username VARCHAR,
    -- joined from USER_DIM
    user_type VARCHAR,
    -- joined from USER_DIM
    post_id VARCHAR,
    content_type VARCHAR,
    -- joined from POST_DIM
    hashtags VARIANT,
    -- joined from POST_DIM
    comment_text VARCHAR,
    video_duration_sec FLOAT,
    watch_time_sec FLOAT,
    event_timestamp TIMESTAMP,
    ingested_at TIMESTAMP
);
-- ── ANALYTICS LAYER ───────────────────────────────────────────────────────────
-- Pre-aggregated results ready for Tableau / BI dashboards.
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
-- top hashtags per 1-minute, 5-minute, and 15-minute windows
CREATE TABLE IF NOT EXISTS ANALYTICS.TRENDING_HASHTAGS (
    hashtag VARCHAR,
    window_size VARCHAR,
    -- '1 minute' / '5 minutes' / '15 minutes'
    window_start TIMESTAMP,
    window_end TIMESTAMP,
    mention_count INTEGER,
    calculated_at TIMESTAMP
);
-- posts that received > 500 likes within any 5-minute window
CREATE TABLE IF NOT EXISTS ANALYTICS.VIRAL_POSTS (
    post_id VARCHAR,
    window_start TIMESTAMP,
    window_end TIMESTAMP,
    like_count INTEGER,
    detected_at TIMESTAMP
);
-- engagement scores per user per 15-minute window
-- engagement_score = likes*1 + comments*3 + shares*5 + video_views*0.5 + follows*2
CREATE TABLE IF NOT EXISTS ANALYTICS.INFLUENCER_RANKING (
    user_id VARCHAR,
    window_start TIMESTAMP,
    window_end TIMESTAMP,
    engagement_score FLOAT,
    like_count INTEGER,
    comment_count INTEGER,
    share_count INTEGER,
    video_view_count INTEGER,
    follow_count INTEGER,
    rank INTEGER,           -- 1 = highest engagement score in this batch window
    calculated_at TIMESTAMP
);
-- per-comment sentiment classification
CREATE TABLE IF NOT EXISTS ANALYTICS.COMMENT_SENTIMENT (
    event_id VARCHAR,
    user_id VARCHAR,
    post_id VARCHAR,
    comment_text VARCHAR,
    sentiment VARCHAR,
    -- POSITIVE / NEUTRAL / NEGATIVE
    event_timestamp TIMESTAMP,
    -- when the comment happened
    processed_at TIMESTAMP -- when Spark classified it
);
-- ── QUICK VERIFY ──────────────────────────────────────────────────────────────
SHOW TABLES IN SCHEMA RAW;
SHOW TABLES IN SCHEMA CURATED;
SHOW TABLES IN SCHEMA ANALYTICS;